region: 'us-east-2'
environment:
  ENV: 'prod'
  REGION: 'us-east-2'
  AWS_ACCOUNT_ID: '000000001' # UPDATE

  SECURITY_GROUP_ID: 'sg-000' # UPDATE
  SUBNET_ID_1: 'subnet-001' # UPDATE
  SUBNET_ID_2: 'subnet-002' # UPDATE

  ALLOWED_ORIGIN: '*' # UPDATE

  DYNAMODB_ENDPOINT: https://dynamodb.us-east-2.amazonaws.com
  SNS_ENDPOINT: 'https://sns.us-east-2.amazonaws.com'
  SQS_ENDPOINT: 'https://sqs.us-east-2.amazonaws.com'

  SUI_PACKAGE_ADDRESS: '0x0000000000000000000000000000000000000000000000000000000000000003' # UPDATE
  SUI_RPC_ENDPOINT: "https://fullnode.mainnet.sui.io/"